
/**
 * CatView - simple page that uses the reusable Carousel component.
 *
 * The images array contains imported image URLs from
 * `src/content/catPhotos/small/` — these are smaller versions
 * generated by the `tools/resize-images.js` script. If you add
 * new original images to `src/content/catPhotos`, run
 * `npm run resize-images` to regenerate the `small/` folder.
 */
import Carousel from '../common/Carousel';

// Import the smaller/resized images. These files live at:
// src/content/catPhotos/small/IMG_*.png
import s1 from '../../content/catPhotos/IMG_0783.png';
import s2 from '../../content/catPhotos/IMG_2007.png';
import s3 from '../../content/catPhotos/IMG_3268.png';
import s4 from '../../content/catPhotos/IMG_4624.png';
import s5 from '../../content/catPhotos/IMG_5014.png';
import s6 from '../../content/catPhotos/IMG_8954.png';

const images = [s1, s2, s3, s4, s5, s6];

function CatView() {
  return (
    <div style={{ padding: 16 }}>
      {/* Page title */}
      <h1 style={{ textAlign: 'center' }}>My Cats</h1>

      {/* Carousel usage: pass an array of image URLs and options
          - autoPlay: set to true to autoplay; false to require manual nav
          - interval: milliseconds between auto-advances
          - maxWidth: maximum width in px (or CSS string) */}
    {/* fitViewport: true makes the carousel height equal to viewport
      minus `viewportOffset` (useful to avoid page scrolling)
    */}
    <Carousel images={images} autoPlay={false} interval={4000} maxWidth={900} fitViewport={true} viewportOffset={120} />
    </div>
  );
}

export default CatView;

